name: deploy-dev
on:
  push:
    branches:
    - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude=".*"
          path: ./
          remote_path: /var/www/html/dev.intothemoss.co.uk/
          remote_host: dept2.co
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }} 